extensions:
  health_check:
  iotauth:
    region: eu-north-1

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        auth:
          authenticator: iotauth
      http:
        endpoint: 0.0.0.0:4318
        auth:
          authenticator: iotauth

processors:
  batch/metrics:
    timeout: 60s

exporters:
  logging:
  awscloudwatchlogs:
    log_group_name: "moon-device"
    log_stream_name: "moon-logs"
    raw_log: true
    region: "eu-central-1"
    log_retention: 180
  awsemf:
    log_retention: 180

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch/metrics]
      exporters: [awsemf]
    logs:
      receivers: [otlp]
      exporters: [awscloudwatchlogs]

  extensions: [iotauth, health_check]
