extensions:
  health_check:
  iotauth:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        auth:
          authenticator: iotauth

processors:
  batch/metrics:
    timeout: 60s

exporters:
  logging:

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch/metrics]
      exporters: [logging]
    logs:
      receivers: [otlp]
      exporters: [logging]

  extensions: [iotauth, health_check]
